//! Shared fake endpoint + helpers (see model_protocol tests).
#![allow(dead_code)]
//! Controlled fake model endpoints for POC-04 / R1-A-16: a raw TCP server
//! with scripted HTTP responses gives full control over chunking, terminal
//! states, failures and drops. Fixtures are hand-written wire samples (not
//! generated by the client serializers under test).

use delta_app::ai::runtime::{
    ModelClient, ModelConnectionConfig, ModelEvent, ModelRequest, Protocol, ProxyPolicy, StopReason,
};
use delta_app::contracts::CancelToken;
use delta_infra::model::{DeltaModelClient, StaticCredentials};
use futures::StreamExt;
use std::sync::atomic::{AtomicUsize, Ordering};
use std::sync::{Arc, Mutex};
use tokio::io::{AsyncReadExt, AsyncWriteExt};
use tokio::net::TcpListener;

// ---- wire fixtures (independent of the serializers under test) --------------

pub const RESP_TEXT_STREAM: &str = "\
event: response.created
data: {\"type\":\"response.created\"}

event: response.output_text.delta
data: {\"type\":\"response.output_text.delta\",\"delta\":\"资产\"}

event: response.output_text.delta
data: {\"type\":\"response.output_text.delta\",\"delta\":\"净值 2068\"}

: keep-alive comment
event: vendor.custom.unknown
data: {\"type\":\"vendor.custom.unknown\"}

event: response.completed
data: {\"type\":\"response.completed\",\"response\":{\"id\":\"resp_1\",\"usage\":{\"input_tokens\":10,\"output_tokens\":5}}}

";

pub const RESP_TOOL_STREAM: &str = "\
event: response.output_item.added
data: {\"type\":\"response.output_item.added\",\"item\":{\"type\":\"function_call\",\"call_id\":\"call_1\",\"name\":\"get_portfolio_summary\"}}

event: response.function_call_arguments.delta
data: {\"type\":\"response.function_call_arguments.delta\",\"item_id\":\"item_1\",\"delta\":\"{\\\"scope\\\":\"}

event: response.function_call_arguments.delta
data: {\"type\":\"response.function_call_arguments.delta\",\"item_id\":\"item_1\",\"delta\":\"{\\\"account_ids\\\":[\\\"a\\\"]}\"}

event: response.output_item.done
data: {\"type\":\"response.output_item.done\",\"item\":{\"type\":\"function_call\",\"call_id\":\"call_1\",\"name\":\"get_portfolio_summary\",\"arguments\":\"{\\\"scope\\\":{\\\"account_ids\\\":[\\\"a\\\"]}}\"}}

event: response.completed
data: {\"type\":\"response.completed\",\"response\":{\"id\":\"resp_2\",\"usage\":{\"input_tokens\":12,\"output_tokens\":8}}}

";

pub const RESP_FAILED_STREAM: &str = "\
event: response.created
data: {\"type\":\"response.created\"}

event: response.output_text.delta
data: {\"type\":\"response.output_text.delta\",\"delta\":\"partial\"}

event: response.failed
data: {\"type\":\"response.failed\",\"response\":{\"error\":{\"message\":\"upstream failure\"}}}

";

pub const CHAT_TEXT_STREAM: &str = "\
data: {\"id\":\"c1\",\"object\":\"chat.completion.chunk\",\"choices\":[{\"index\":0,\"delta\":{\"role\":\"assistant\",\"content\":\"你好\"},\"finish_reason\":null}]}

data: {\"id\":\"c1\",\"object\":\"chat.completion.chunk\",\"choices\":[{\"index\":0,\"delta\":{\"content\":\"，世界\"},\"finish_reason\":null}]}

data: {\"id\":\"c1\",\"object\":\"chat.completion.chunk\",\"choices\":[{\"index\":0,\"delta\":{},\"finish_reason\":\"stop\"}],\"usage\":{\"prompt_tokens\":7,\"completion_tokens\":3}}

data: [DONE]

";

pub const CHAT_TOOL_STREAM: &str = "\
data: {\"id\":\"c2\",\"choices\":[{\"index\":0,\"delta\":{\"tool_calls\":[{\"index\":0,\"id\":\"call_9\",\"type\":\"function\",\"function\":{\"name\":\"query_trades\",\"arguments\":\"{\\\"lim\"}}]},\"finish_reason\":null}]}

data: {\"id\":\"c2\",\"choices\":[{\"index\":0,\"delta\":{\"tool_calls\":[{\"index\":0,\"function\":{\"arguments\":\"it\\\":10}\"}}]},\"finish_reason\":null}]}

data: {\"id\":\"c2\",\"choices\":[{\"index\":0,\"delta\":{},\"finish_reason\":\"tool_calls\"}]}

data: [DONE]

";

// ---- fake server -------------------------------------------------------------

/// A scripted endpoint: serves the given raw HTTP responses in order.
pub struct FakeEndpoint {
    pub url: String,
    pub requests: Arc<AtomicUsize>,
    /// Captured request bodies in arrival order, so tests can assert on
    /// what the client actually sent (roles, pairing, no secrets).
    pub bodies: Arc<Mutex<Vec<String>>>,
    handle: tokio::task::JoinHandle<()>,
    port: u16,
}

pub struct ScriptedResponse {
    /// HTTP status line code.
    pub status: u16,
    pub headers: Vec<(String, String)>,
    pub body: String,
    /// Close without writing the full body (mid-stream drop).
    pub drop_after_bytes: Option<usize>,
    /// Delay before sending the status line. Counts against the total timeout.
    pub delay_ms: u64,
    /// Delay after the headers, before the first body byte. Counts against
    /// the idle (read) timeout.
    pub body_delay_ms: u64,
    /// Pause between SSE records so a long stream stays active.
    pub pace_ms: u64,
}

impl ScriptedResponse {
    pub fn sse(body: &str) -> Self {
        Self {
            status: 200,
            headers: vec![("content-type".into(), "text/event-stream".into())],
            body: body.to_string(),
            drop_after_bytes: None,
            delay_ms: 0,
            body_delay_ms: 0,
            pace_ms: 0,
        }
    }
    pub fn status(status: u16) -> Self {
        Self {
            status,
            headers: vec![],
            body: "{\"error\":{\"message\":\"rejected\"}}".into(),
            drop_after_bytes: None,
            delay_ms: 0,
            body_delay_ms: 0,
            pace_ms: 0,
        }
    }
}

pub async fn spawn_endpoint(script: Vec<ScriptedResponse>) -> FakeEndpoint {
    let listener = TcpListener::bind("127.0.0.1:0").await.unwrap();
    let port = listener.local_addr().unwrap().port();
    let requests = Arc::new(AtomicUsize::new(0));
    let req_clone = requests.clone();
    let bodies = Arc::new(Mutex::new(Vec::new()));
    let bodies_clone = bodies.clone();
    let handle = tokio::spawn(async move {
        let mut script = script;
        loop {
            let (mut socket, _) = match listener.accept().await {
                Ok(v) => v,
                Err(_) => return,
            };
            req_clone.fetch_add(1, Ordering::SeqCst);
            // Read the request head (and body if content-length given) so the
            // client can send before we respond.
            let mut buf = Vec::new();
            loop {
                let mut chunk = [0u8; 8192];
                let n = socket.read(&mut chunk).await.unwrap_or(0);
                if n == 0 {
                    break;
                }
                buf.extend_from_slice(&chunk[..n]);
                let text = buf.as_slice();
                let got = buf.len();
                let head_end = text
                    .windows(4)
                    .position(|w| w == b"\r\n\r\n")
                    .map(|p| p + 4);
                if let Some(hend) = head_end {
                    let cl = String::from_utf8_lossy(&text[..hend])
                        .to_ascii_lowercase()
                        .lines()
                        .find_map(|l| {
                            l.strip_prefix("content-length:")
                                .map(|v| v.trim().to_string())
                        });
                    let need = hend + cl.and_then(|v| v.parse::<usize>().ok()).unwrap_or(0);
                    if got >= need {
                        let body = String::from_utf8_lossy(&text[hend..need]).into_owned();
                        bodies_clone.lock().unwrap().push(body);
                        break;
                    }
                }
            }
            let resp = if script.is_empty() {
                ScriptedResponse::status(500)
            } else {
                script.remove(0)
            };
            if resp.delay_ms > 0 {
                tokio::time::sleep(std::time::Duration::from_millis(resp.delay_ms)).await;
            }
            let reason = match resp.status {
                200 => "OK",
                302 => "Found",
                401 => "Unauthorized",
                429 => "Too Many Requests",
                500 => "Internal Server Error",
                _ => "Error",
            };
            let mut head = format!("HTTP/1.1 {} {}\r\n", resp.status, reason);
            let has_ct = resp
                .headers
                .iter()
                .any(|(k, _)| k.eq_ignore_ascii_case("content-type"));
            if !has_ct {
                head.push_str("content-type: application/json\r\n");
            }
            for (k, v) in &resp.headers {
                head.push_str(&format!("{k}: {v}\r\n"));
            }
            head.push_str("connection: close\r\n\r\n");
            let _ = socket.set_nodelay(true);
            let _ = socket.write_all(head.as_bytes()).await;
            let _ = socket.flush().await;
            if resp.body_delay_ms > 0 {
                tokio::time::sleep(std::time::Duration::from_millis(resp.body_delay_ms)).await;
            }
            if let Some(cut) = resp.drop_after_bytes {
                let cut = cut.min(resp.body.len());
                let _ = socket.write_all(&resp.body.as_bytes()[..cut]).await;
                let _ = socket.flush().await;
                // Abrupt close: no terminal event, no [DONE].
                return;
            }
            if resp.pace_ms == 0 {
                let _ = socket.write_all(resp.body.as_bytes()).await;
            } else {
                for (i, record) in resp.body.split("\n\n").enumerate() {
                    if record.is_empty() {
                        continue;
                    }
                    if i > 0 {
                        tokio::time::sleep(std::time::Duration::from_millis(resp.pace_ms)).await;
                    }
                    let _ = socket.write_all(record.as_bytes()).await;
                    let _ = socket.write_all(b"\n\n").await;
                    let _ = socket.flush().await;
                }
            }
            let _ = socket.flush().await;
        }
    });
    FakeEndpoint {
        url: format!("http://127.0.0.1:{port}"),
        requests,
        bodies,
        handle,
        port,
    }
}

impl FakeEndpoint {
    pub async fn shutdown(self) {
        self.handle.abort();
        let _ = self.handle.await;
    }
}

// ---- helpers -------------------------------------------------------------------

pub fn responses_connection(url: &str) -> ModelConnectionConfig {
    ModelConnectionConfig {
        id: "conn-test".into(),
        protocol: Protocol::OpenaiResponses,
        base_url: url.into(),
        model_id: "delta-test-model".into(),
        credential_ref: "test-keyring-ref".into(),
        context_window_tokens: 8192,
        connect_timeout_secs: 5,
        idle_timeout_secs: 30,
        request_timeout_secs: 10,
        // Tests never go through a proxy, whatever this machine configures.
        proxy: ProxyPolicy::Direct,
    }
}

pub fn chat_connection(url: &str) -> ModelConnectionConfig {
    ModelConnectionConfig {
        protocol: Protocol::OpenaiChatCompletions,
        ..responses_connection(url)
    }
}

pub fn client_for(conn: ModelConnectionConfig) -> DeltaModelClient {
    DeltaModelClient::new(
        conn,
        Arc::new(StaticCredentials {
            key: "test-secret-key".into(),
        }),
    )
    .unwrap()
}

pub fn sample_request(protocol: Protocol) -> ModelRequest {
    ModelRequest {
        request_id: "req-1".into(),
        run_id: "run-1".into(),
        generation: 1,
        connection_id: "conn-test".into(),
        instructions: "You are a read-only financial analysis assistant.".into(),
        input_items: vec![serde_json::json!({"role":"user","content":"解释当前损益"})],
        tool_definitions: vec![serde_json::json!({
            "type": "function",
            "name": "get_portfolio_summary",
            "description": "summary",
            "parameters": {"type":"object","properties":{}}
        })],
        max_output_tokens: None,
    }
    .with_protocol(protocol)
}

trait WithProtocol {
    fn with_protocol(self, p: Protocol) -> ModelRequest;
}

impl WithProtocol for ModelRequest {
    fn with_protocol(self, _p: Protocol) -> ModelRequest {
        self
    }
}

pub async fn collect(client: &DeltaModelClient, req: ModelRequest) -> Vec<ModelEvent> {
    let cancel = CancelToken::new();
    let mut stream = client.stream(req, cancel).unwrap();
    let mut out = Vec::new();
    while let Some(ev) = stream.next().await {
        if std::env::var("DBG_EVENTS").is_ok() {
            eprintln!("EVENT: {ev:?}");
        }
        out.push(ev);
        if matches!(
            out.last(),
            Some(ModelEvent::Completed { .. }) | Some(ModelEvent::Failed { .. })
        ) {
            break;
        }
    }
    out
}

pub fn assert_no_retry_on_events(events: &[ModelEvent]) {
    // Contract: visible events then failure must not be replayed — verified
    // via request counts in individual tests.
    let _ = events;
}

pub fn stop_reason_of(events: &[ModelEvent]) -> Option<StopReason> {
    events.iter().find_map(|e| match e {
        ModelEvent::Completed { stop_reason } => Some(*stop_reason),
        _ => None,
    })
}

pub fn failed_of(events: &[ModelEvent]) -> Option<String> {
    events.iter().find_map(|e| match e {
        ModelEvent::Failed { error } => Some(error.safe_message.clone()),
        _ => None,
    })
}

pub fn text_of(events: &[ModelEvent]) -> String {
    events
        .iter()
        .filter_map(|e| match e {
            ModelEvent::TextDelta { delta } => Some(delta.clone()),
            _ => None,
        })
        .collect()
}
